#!/bin/bash

line=`pidof hl2_linux`
arr=($line)
inst=$1
if [ $# == 0 ]; then 
	inst=0
fi

if [ ${#arr[@]} == 0 ]; then
	echo tf2 isn\'t running!
	exit
fi

if [ $inst -gt ${#arr[@]} ] || [ $inst == ${#arr[@]} ]; then
	echo wrong index!
	exit
fi

proc=${arr[$inst]}

echo Running instances: ${arr[@]}
echo Attaching to $proc

sudo ./detach $inst libcathook.so

if grep -q $(realpath libcathook.so) /proc/$proc/maps; then
  echo already loaded
  exit
fi

echo loading $(realpath libcathook.so) to $proc
gdb -n -q -batch \
  -ex "attach $proc" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$(realpath libcathook.so)\", 1)" \
  -ex "call dlerror()" \
  -ex 'print (char *) $2' \
  -ex "continue" \
  -ex "backtrace"