#!/bin/bash

line=`pidof hl2_linux`
arr=($line)
inst=$1
if [ $# == 0 ]; then 
	inst=0
fi

if [ ${#arr[@]} == 0 ]; then
	echo tf2 isn\'t running!
	exit
fi

if [ $inst -gt ${#arr[@]} ] || [ $inst == ${#arr[@]} ]; then
	echo wrong index!
	exit
fi

echo Running instances: ${arr[@]}
echo Attaching to ${arr[$1]}

if grep -q $(realpath libcathook.so) /proc/${arr[$1]}/maps; then
  echo already loaded
  exit
fi

echo loading $(realpath libcathook.so) to ${arr[$1]}
gdb -n -q -batch \
  -ex "attach ${arr[$1]}" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$(realpath libcathook.so)\", 1)" \
  -ex "call dlerror()" \
  -ex 'print (char *) $2' \
  -ex "detach" \
  -ex "quit"

